### ISSUE TITLE
Cards on top of the others

### ISSUE THREAD

**Issue by zenoualex** [tomosterlund/qalendar#139] opened 2023-03-15 17:27 UTC
**Describe the bug**
I have an app that has many events and the time of the event can be long one.
So if I click on week mode the cards are one on top of the other.
here is one screen shot

![Screenshot_2](https://user-images.githubusercontent.com/17253705/225392330-ea535d19-506f-4fc1-8bac-8bdeda5744ae.png)

Is there any way to make it look better?

Thank you in advance.

**Comment by tomosterlund** [comment] 2023-03-15 21:09
Hi @zenoualex 

This is not a bug, but the expected behavior for all concurrent events. The placement of such events in Qalendar, is strongly based on the concept of concurrent events in the Google-calendar, where it looks like this:

![Bildschirm­foto 2023-03-15 um 22 03 18](https://user-images.githubusercontent.com/63011648/225442286-50016fda-8bbf-4a86-9b9d-6efd1af83b14.png)

For now I'll go ahead and close this issue, but if you have a more specific idea for how to solve spacing of events running parallelly, feel free to open this issue again, but with a more concrete example. Maybe you can play around with the calendar in your dev tools, locally override some styles, and then post a suggestion here?

**Closed by tomosterlund** 2023-03-15 21:09 UTC
